import "./globals.css";
import { PhotoStateProvider } from "@/context/PhotoState";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="true">
        <PhotoStateProvider>{children}</PhotoStateProvider>
      </body>
    </html>
  );
}
